"use strict";

var test_PH_NX2_NXA_tracklist = [];

var test_PH_NX2_NXA_arcade = 
[
  [ "103", "", "", "K-Pop", "Forever Love", "Fin.K.L", "138", "", "1", "", "", "", "13", "E1", "1", "", "", "", "13", "", "", "", "", "Forever Love", "103" ],
  [ "109", "", "", "K-Pop", "Funky Tonight", "Clon", "105", "", "", "4", "12", "4", "", "E6", "", "4", "12", "4", "", "", "", "", "", "Funky Tonight", "109" ],
  [ "111", "", "", "K-Pop", "Hatred", "Novasonic", "136", "WorldMax (NX2)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Hatred", "111" ],
  [ "112", "", "", "K-Pop", "Another Truth", "Novasonic", "136", "", "3", "5", "15", "6", "16", "", "4", "5", "15", "6", "16", "", "", "", " Math", "Another Truth", "112" ],
  [ "202", "", "", "Original", "Hate", "BanYa", "90.4", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Hate", "202" ],
  [ "204", "", "", "Original", "Final Audition", "BanYa", "130.5", "", "3", "7", "15", "3", "16", "", "3", "7", "17", "3", "17", "", "", "", " Mem.", "Final Audition", "204" ],
  [ "205", "", "", "Original", "Extravaganza", "BanYa", "195", "", "", "10", "12", "13", "18", "", "", "10", "11", "12", "17", "", "", "", "", "Extravaganza", "205" ],
  [ "212", "", "", "K-Pop", "Com'back", "Sechskies", "158", "", "", "6", "15", "", "16", "", "", "6", "15", "", "16", "", "", "", " Math", "Com'back", "212" ],
  [ "301", "", "", "Original", "Final Audition 2", "BanYa", "130.6", "", "", "8", "10", "8", "17", "", "", "8", "10", "8", "17", "", "", "", " Obs.", "Final Audition 2", "301" ],
  [ "302", "", "", "Original", "Naissance", "BanYa", "135.5", "", "", "7", "11", "7", "14", "", "", "7", "10", "7", "15", "", "", "", "", "Naissance", "302" ],
  [ "303", "", "", "Original", "Turkey March", "BanYa", "150", "", "", "7", "12", "9", "18", "", "", "7", "12", "9", "19", "", "", "", " Obs.", "Turkey March", "303" ],
  //[ "304", "", "", "Original", "With My Lover", "BanYa", "124", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "With My Lover", "304" ],
  //[ "305", "", "", "Original", "An Interesting View", "BanYa", "160", "WorldMax (NXA beta v.)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "An Interesting View", "305" ],
  //[ "306", "", "", "Original", "Nightmare", "BanYa", "80", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Nightmare", "306" ],
  //[ "307", "", "", "Original", "Close Your Eyes", "BanYa", "105", "WorldMax (NXA beta v.)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Close Your Eyes", "307" ],
  //[ "308", "", "", "Original", "Free Style", "BanYa", "99", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Free Style", "308" ],
  //[ "309", "", "", "Original", "Midnight Blue", "BanYa", "80", "WorldMax (NXA beta v.)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Midnight Blue", "309" ],
  [ "310", "", "", "Original", "She Likes Pizza", "BanYa", "229.6", "", "", "7", "11", "8", "16", "", "", "8", "9", "9", "16", "", "", "", " Obs.", "She Likes Pizza", "310" ],
  [ "311", "", "", "Original", "Pumping Up", "BanYa", "135", "WorldMax, Easy Station, Brain Shower (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", " Mem.", "Pumping Up", "311" ],
  [ "312", "", "", "K-Pop", "Don't Bother Me", "Tashannie", "110", "", "3", "6", "12", "6", "", "E4", "2", "6", "10", "6", "", "", "", "", " Mem.", "Don't Bother Me", "312" ],
  [ "313", "", "", "K-Pop", "Love Song", "Yu Seung Jun (Steve Yoo)", "118", "Easy Station (NXA beta v.)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Love Song", "313" ],
  [ "318", "", "", "K-Pop", "We Are", "Deux", "115.9", "", "", "5", "13", "6", "14", "E7", "", "5", "12", "6", "13", "", "", "", "", "We Are", "318" ],
  [ "401", "", "", "Original", "Oh! Rosa", "BanYa", "148", "WorldMax, Brain Shower (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", " Mem.", "Oh! Rosa", "401" ],
  [ "402", "", "", "Original", "First Love", "BanYa", "104", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "First Love", "402" ],
  [ "404", "", "", "Original", "Solitary", "BanYa", "136", "", "3", "5", "9", "7", "16", "", "3", "6", "9", "7", "16", "", "", "", "", "Solitary", "404" ],
  [ "405", "", "", "Original", "Mr. Larpus", "BanYa", "190", "", "4", "11", "14", "14", "17", "", "5", "11", "14", "14", "17", "", "", "", "", "Mr. Larpus", "405" ],
  [ "501", "", "", "Original", "Pump Jump", "BanYa", "106", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Pump Jump", "501" ],
  [ "502", "", "", "Original", "N", "BanYa", "104/208", "", "2", "5", "16", "5", "", "", "2", "5", "16", "5", "", "", "", "", "", "N", "502" ],
  [ "503", "", "", "Original", "Rolling Christmas", "BanYa", "142", "Training Station (NX2) Easy Station, WorldMax (NXA)", "", "", "", "", "", "E5", "", "", "", "", "", "", "", "", "", "Rolling Christmas", "503" ],
  [ "504", "", "", "Original", "All I Want For X-Mas", "BanYa", "130", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "All I Want For X-Mas", "504" ],
  [ "505", "", "", "Original", "Beethoven Virus", "BanYa", "162", "", "3", "7", "13", "8", "20", "E4", "4", "7", "13", "8", "20", "", "", "", " Math", "Beethoven Virus", "505" ],
  [ "507", "", "", "K-Pop", "Come Back to Me", "Deux", "116.4", "", "2", "5", "11", "6", "13", "E5", "2", "5", "11", "6", "13", "", "", "", " Mem.", "Come Back to Me", "507" ],
  [ "516", "", "", "K-Pop", "Slam", "Novasonic", "131.99", "", "3", "6", "18", "6", "20", "", "3", "6", "17", "6", "20", "", "", "", "", "Slam", "516" ],
  [ "701", "", "", "Original", "Dr. M", "BanYa", "145", "", "3", "7", "11", "9", "16", "E4", "4", "7", "12", "11", "16", "", "", "", " Math", "Dr. M", "701" ],
  [ "704", "", "", "Original", "Love is a Danger Zone", "BanYa", "140", "", "3", "5", "19", "6", "20", "", "4", "7", "19", "6", "20", "", "", "", " Mem.", "Love is a Danger Zone", "704" ],
  //[ "705", "", "", "Original", "Maria", "BanYa", "136", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Maria", "705" ],
  //[ "706", "", "", "Original", "Mission Possible", "BanYa", "124", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Mission Possible", "706" ],
  //[ "707", "", "", "Original", "My Way", "BanYa", "118", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "My Way", "707" ],
  [ "708", "", "", "Original", "Point Break", "BanYa", "92", "", "3", "6", "9", "6", "13", "E4", "3", "6", "9", "6", "13", "", "", "", " Mem.", "Point Break", "708" ],
  [ "709", "", "", "Original", "Street Show Down", "BanYa", "124", "No exclusivity (NX2) WorldMax (NXA)", "4", "7", "8", "6", "13", "", "", "", "", "", "", "", "", "", "", "Street Show Down", "709" ],
  [ "711", "", "", "Original", "Winter", "BanYa", "168", "", "4", "9", "14", "10", "19", "E8", "4", "8", "15", "11", "19", "", "", "", " Mem.", "Winter", "711" ],
  [ "712", "", "", "Original", "Will o' the Wisp", "BanYa", "210", "", "5", "10", "13", "13", "19", "", "5", "10", "13", "13", "19", "", "", "", " Math", "Will o' the Wisp", "712" ],
  //[ "713", "", "", "Original", "Till The End of Time", "BanYa", "140", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Till The End of Time", "713" ],
  //[ "714", "", "", "Original", "Oy Oy Oy", "BanYa", "148", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Oy Oy Oy", "714" ],
  //[ "715", "", "", "Original", "We Will Meet Again", "BanYa", "118", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "We Will Meet Again", "715" ],
  [ "716", "", "", "Original", "Miss's Story", "BanYa", "111", "No exclusivity (NX2) WorldMax (NXA)", "3", "5", "12", "3", "", "", "", "", "", "", "", "", "", "", "", "Miss's Story", "716" ],
  [ "718", "", "", "Original", "Dance With Me", "BanYa", "122", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Dance With Me", "718" ],
  [ "735", "", "", "Original", "Vook", "BanYa", "184", "", "4", "8", "14", "16", "18", "", "5", "9", "15", "17", "18", "", "", "", " Math", "Vook", "735" ],
  [ "736", "", "", "Original", "Csikos Post", "BanYa", "180", "Training Station (NX2) Easy Station, WorldMax, Brain Shower (NXA)", "", "", "", "", "", "E6", "", "", "", "", "", "", "", "", " Mem.", "Csikos Post", "736" ],
  [ "802", "", "", "Original", "Bee", "BanYa", "160", "", "3", "8", "15", "11", "21", "E6", "4", "11", "15", "11", "21", "", "", "", " Mem.", "Bee", "802" ],
  //[ "807", "", "", "Original", "D Gang", "BanYa", "150", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "D Gang", "807" ],
  //[ "811", "", "", "Original", "Hello", "BanYa", "140", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Hello", "811" ],
  [ "820", "", "", "Original", "Beat of the War", "BanYa", "186/140/202", "No exclusivity (NX2) WorldMax (NXA)", "5", "10", "15", "12", "19", "", "", "", "", "", "", "", "", "", "", "Beat of the War", "820" ],
  [ "826", "", "", "Original", "Come to Me", "BanYa", "100/107/100", "", "3", "6", "11", "6", "13", "", "3", "6", "11", "6", "13", "", "", "", "", "Come to Me", "826" ],
  [ "902", "", "", "K-Pop", "Circus Magic", "Crying Nut", "141", "", "3", "8", "14", "9", "", "", "", "", "", "", "", "", "", "", "", "Circus Magic", "902" ],
  [ "906", "", "", "K-Pop", "Starian", "Duke", "134.9", "", "", "7", "13", "9", "", "", "", "7", "13", "9", "", "", "", "", " Math", "Starian", "906" ],
  [ "909", "", "", "K-Pop", "Mistake", "U'Two", "110", "", "1", "6", "", "6", "13", "E3", "1", "6", "", "6", "12", "", "", "", "", "Mistake", "909" ],
  [ "911", "", "", "Original", "Chicken Wing", "BanYa", "200", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Chicken Wing", "911" ],
  [ "919", "", "", "K-Pop", "Lazenca, Save Us", "N.Ex.T", "85.1", "", "2", "5", "", "5", "", "E4", "3", "6", "", "5", "", "", "", "", "", "Lazenca, Save Us", "919" ],
  [ "922", "", "", "Original", "Final Audition Episode 1", "BanYa", "189", "", "", "8", "15", "11", "21", "", "", "8", "15", "11", "21", "", "", "", "", "Final Audition Episode 1", "922" ],
  [ "A01", "", "", "Original", "Final Audition 3 U.F", "BanYa", "130.5", "", "3", "6", "14", "5", "17", "", "3", "6", "14", "5", "17", "", "", "", " Math", "Final Audition 3 U.F", "A01" ],
  [ "A02", "", "", "Original", "Naissance 2", "BanYa", "128", "", "3", "6", "13", "5", "15", "", "3", "6", "13", "5", "15", "", "", "", "", "Naissance 2", "A02" ],
  [ "A03", "", "", "Original", "Monkey Fingers", "BanYa", "186", "", "3", "7", "15", "7", "17", "", "5", "8", "15", "7", "17", "", "", "", "", "Monkey Fingers", "A03" ],
  [ "A04", "", "", "Original", "Blazing", "BanYa", "157", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Blazing", "A04" ],
  [ "A05", "", "", "Original", "Pump Me Amadeus", "BanYa", "170", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Pump Me Amadeus", "A05" ],
  [ "A06", "", "", "Original", "X-Treme", "BanYa", "162", "", "4", "7", "14", "9", "19", "", "5", "9", "14", "9", "19", "", "", "", "", "X-Treme", "A06" ],
  [ "A07", "", "", "Original", "Get Up!", "BanYa", "180", "", "4", "7", "15", "7", "18", "", "", "", "", "", "", "", "", "", "", "Get Up!", "A07" ],
  [ "A08", "", "", "K-Pop", "Dignity", "Crash", "195", "", "4", "11", "20", "15", "23", "", "5", "12", "20", "13", "23", "", "", "", "", "Dignity", "A08" ],
  [ "A11", "", "", "K-Pop", "What Do You Really Want?", "Crash", "110", "", "2", "9", "20", "11", "14", "", "3", "9", "19", "11", "16", "", "", "", "", "What Do You Really Want?", "A11" ],
  [ "A12", "", "", "K-Pop", "Go", "U;nee", "138", "", "3", "6", "12", "3", "13", "", "3", "7", "12", "3", "13", "", "", "", "", "Go", "A12" ],
  [ "A14", "", "", "Pop", "Kiss Me", "Debbie Scott", "126", "Training Station (NX2)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Kiss Me", "A14" ],
  [ "A15", "", "", "Pop", "Essa Maneira", "Kaoma", "150", "", "3", "7", "13", "9", "14", "", "", "", "", "", "", "", "", "", "", "Essa Maneira", "A15" ],
  [ "A17", "", "", "Pop", "La Cubanita", "Los Ninos de Sara", "120", "", "4", "9", "13", "10", "16", "", "", "", "", "", "", "", "", "", "", "La Cubanita", "A17" ],
  [ "A18", "", "", "Pop", "Shake it Up", "ROD", "120", "", "4", "9", "15", "3", "19", "", "", "", "", "", "", "", "", "", "", "Shake it Up", "A18" ],
  [ "A20", "", "", "Pop", "Power of Dream", "Victoria", "122", "", "1", "7", "14", "6", "15", "", "", "", "", "", "", "", "", "", "", "Power of Dream", "A20" ],
  [ "A21", "", "", "Pop", "Watch Out", "Victoria", "109", "", "3", "6", "10", "6", "12", "", "", "", "", "", "", "", "", "", "", "Watch Out", "A21" ],
  [ "A23", "", "", "Pop", "Soca Make Yuh Ram Ram", "General Grant", "108", "", "3", "5", "10", "5", "12", "", "", "", "", "", "", "", "", "", "", "Soca Make Yuh Ram Ram", "A23" ],
  [ "B01", "", "", "K-Pop", "Greenhorn", "Lexy", "109", "", "2", "4", "13", "5", "15", "E2", "2", "4", "13", "5", "13", "", "", "", " Mem.", "Greenhorn", "B01" ],
  [ "B02", "", "", "K-Pop", "Hot", "1TYM", "98", "", "2", "5", "11", "4", "12", "E5", "2", "5", "10", "4", "12", "", "", "", "", "Hot", "B02" ],
  [ "B03", "", "", "K-Pop", "Pray", "Som2", "122", "", "2", "4", "9", "4", "11", "", "", "", "", "", "", "", "", "", "", "Pray", "B03" ],
  [ "B05", "", "", "K-Pop", "Drunken in Melody", "Eun Ji Won", "94.3", "", "2", "5", "", "5", "", "E3", "3", "5", "", "5", "", "", "", "", "", "Drunken in Melody", "B05" ],
  [ "B06", "", "", "K-Pop", "Deja Vu", "Som2", "115", "", "3", "5", "14", "6", "14", "", "3", "6", "13", "6", "13", "", "", "", "", "Deja Vu", "B06" ],
  [ "B08", "", "", "K-Pop", "Sajahu", "Lee Hyun Do", "126", "", "3", "5", "13", "5", "14", "E6", "3", "5", "13", "5", "14", "", "", "", "", "Sajahu", "B08" ],
  [ "B09", "", "", "K-Pop", "Typhoon", "Lee Hyun Do", "112", "No exclusivity (NX2) WorldMax [Full Song only] (NXA)", "2", "5", "10", "5", "13", "", "", "", "", "", "", "", "", "", "", "Typhoon", "B09" ],
  [ "B13", "", "", "K-Pop", "I'll Give You All My Love", "WAX", "164/82", "", "3", "7", "16", "7", "18", "E4", "3", "7", "16", "7", "18", "", "", "", " Math", "I'll Give You All My Love", "B13" ],
  [ "B16", "", "", "Original", "J Bong", "BanYa", "140", "No exclusivity (NX2) WorldMax (NXA)", "5", "7", "13", "5", "17", "", "", "", "", "", "", "", "", "", "", "J Bong", "B16" ],
  [ "B17", "", "", "Original", "Hi-Bi", "BanYa", "145", "", "4", "8", "14", "8", "18", "", "3", "8", "15", "8", "18", "", "", "", " Obs.", "Hi-Bi", "B17" ],
  [ "B18", "", "", "Original", "Solitary 2", "BanYa", "136", "", "3", "6", "17", "6", "19", "", "3", "6", "17", "6", "18", "", "", "", "", "Solitary 2", "B18" ],
  [ "B19", "", "", "Original", "Canon-D", "BanYa", "160", "", "3", "5", "20", "9", "22", "E5", "4", "6", "20", "10", "22", "", "", "", " Math", "Canon-D", "B19" ],
  [ "B20", "", "", "Pop", "Le Code de Bonne Conduite", "Manresa", "171", "", "4", "5", "12", "8", "15", "", "", "", "", "", "", "", "", "", "", "Le Code de Bonne Conduite", "B20" ],
  [ "C01", "", "", "Original", "Beat of the War 2", "BanYa", "190/140/120/160", "", "4", "9", "16", "11", "19", "", "5", "10", "16", "12", "19", "", "", "", "", "Beat of the War 2", "C01" ],
  [ "C02", "", "", "Original", "Moonlight", "BanYa", "180/45/90", "", "", "8", "19", "11", "21", "", "", "10", "19", "11", "21", "", "", "", "", "Moonlight", "C02" ],
  [ "C03", "", "", "Original", "Witch Doctor", "BanYa", "195/390", "", "", "", "17", "", "23", "", "", "", "16", "", "23", "", "", "", "", "Witch Doctor", "C03" ],
  [ "C04", "", "", "Original", "Love is a Danger Zone 2", "BanYa", "162", "", "6", "15", "21", "18", "23", "", "7", "15", "21", "17", "23", "", "", "", " Obs.", "Love is a Danger Zone 2", "C04" ],
  [ "C05", "", "", "Original", "Phantom", "BanYa", "136/34", "", "", "10", "18", "7", "19", "", "", "12", "18", "7", "19", "", "", "", "", "Phantom", "C05" ],
  [ "C06", "", "", "Original", "Papa Gonzales", "BanYa", "145", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Papa Gonzales", "C06" ],
  [ "C07", "", "", "Original", "Jump", "BanYa", "96", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Jump", "C07" ],
  [ "C08", "", "", "K-Pop", "Emergency", "Drunken Tiger", "110", "", "2", "5", "12", "5", "14", "", "", "", "", "", "", "", "", "", "", "Emergency", "C08" ],
  [ "C09", "", "", "K-Pop", "My Friend", "Cho PD", "127", "", "3", "4", "12", "5", "14", "", "", "", "", "", "", "", "", "", "", "My Friend", "C09" ],
  [ "C10", "", "", "K-Pop", "Wuthering Heights", "Eugene", "138", "", "2", "4", "", "3", "", "", "", "", "", "", "", "", "", "", "", "Wuthering Heights", "C10" ],
  [ "C11", "", "", "K-Pop", "Do it Yourself", "LazyBone", "106/53", "", "", "6", "13", "7", "14", "", "", "", "", "", "", "", "", "", "", "Do it Yourself", "C11" ],
  [ "C12", "", "", "K-Pop", "What's Going On", "Turtles", "130", "", "3", "3", "7", "5", "8", "", "", "", "", "", "", "", "", "", "", "What's Going On", "C12" ],
  [ "C14", "", "", "K-Pop", "Chung Hwa Ban Jeom", "Louis", "149.5", "", "1", "5", "12", "3", "15", "", "", "", "", "", "", "", "", "", "", "Chung Hwa Ban Jeom", "C14" ],
  [ "C15", "", "", "K-Pop", "Mr. Fire Fighter", "Spooky Banana", "158/79/632", "", "2", "7", "13", "8", "15", "", "2", "7", "13", "8", "15", "", "", "", "", "Mr. Fire Fighter", "C15" ],
  [ "C16", "", "", "K-Pop", "Footprints", "T.O", "135", "", "", "5", "11", "5", "11", "", "", "", "", "", "", "", "", "", "", "Footprints", "C16" ],
  [ "C17", "", "", "K-Pop", "Oh My!", "Jang Yoon Jung", "112", "", "2", "4", "10", "4", "11", "", "", "", "", "", "", "", "", "", "", "Oh My!", "C17" ],
  [ "C18", "", "", "K-Pop", "Enter the Dragon", "JTL", "110", "", "2", "5", "14", "5", "17", "E7", "2", "5", "14", "5", "17", "", "", "", "", "Enter the Dragon", "C18" ],
  [ "C19", "", "", "K-Pop", "Storm", "Perry", "96", "", "2", "5", "12", "4", "13", "", "3", "5", "12", "4", "13", "", "", "", "", "Storm", "C19" ],
  [ "C20", "", "", "K-Pop", "Turn Around", "Mina", "113", "", "2", "4", "13", "5", "14", "", "", "", "", "", "", "", "", "", "", "Turn Around", "C20" ],
  [ "D01", "", "", "Original", "Witch Doctor #1", "Yahpp", "122", "", "3", "7", "14", "5", "19", "", "3", "7", "14", "5", "19", "", "", "", " Obs.", "Witch Doctor #1", "D01" ],
  [ "D02", "", "", "Original", "Arch of Darkness", "Yahpp", "135.9", "", "3", "7", "14", "4", "17", "", "3", "7", "14", "4", "16", "", "", "", " Mem.", "Arch of Darkness", "D02" ],
  [ "D03", "", "", "Original", "Chimera", "Yahpp", "210", "", "8", "17", "23", "20", "25", "", "7", "16", "23", "21", "??", "", "", "", " Math", "Chimera", "D03" ],
  [ "D04", "", "", "K-Pop", "Go Back", "Dynamic Duo", "112", "", "1", "4", "9", "4", "10", "", "", "", "", "", "", "", "", "", "", "Go Back", "D04" ],
  [ "D05", "", "", "K-Pop", "Fly", "Epik High", "128", "", "3", "5", "14", "4", "16", "", "", "", "", "", "", "", "", "", "", "Fly", "D05" ],
  [ "D06", "", "", "K-Pop", "One Night", "DJ DOC", "132", "", "2", "5", "13", "4", "14", "E3", "2", "5", "13", "4", "14", "", "", "", " Obs.", "One Night", "D06" ],
  [ "D07", "", "", "K-Pop", "U Inside My Dim Memory", "Hyun Jin Young vs. Yahpp", "118", "No exclusivity (NX2) Beta version (NXA)", "3", "6", "14", "4", "18", "", "", "", "", "", "", "", "", "", "", "U Inside My Dim Memory", "D07" ],
  [ "D08", "", "", "K-Pop", "Free!", "Jiny", "174.6", "", "4", "7", "15", "8", "18", "", "", "", "", "", "", "", "", "", "", "Free!", "D08" ],
  [ "D09", "", "", "K-Pop", "Lovely", "Kim Jong Kook", "188", "", "4", "5", "12", "4", "13", "", "", "", "", "", "", "", "", "", "", "Lovely", "D09" ],
  [ "D10", "", "", "K-Pop", "Terminal Depository", "Ururbu Project", "100/138", "", "3", "6", "13", "5", "16", "", "", "", "", "", "", "", "", "", "", "Terminal Depository", "D10" ],
  [ "D11", "", "", "K-Pop", "For You", "N.Ex.T", "160", "", "1", "5", "14", "5", "20", "", "", "", "", "", "", "", "", "", "", "For You", "D11" ],
  [ "D12", "", "", "K-Pop", "Snow Dream", "Apple Jam", "170", "", "3", "5", "13", "7", "13", "", "", "", "", "", "", "", "", "", "", "Snow Dream", "D12" ],
  [ "D13", "", "", "K-Pop", "Handsome Character That Pass", "May", "125", "", "2", "4", "18", "3", "15", "", "", "", "", "", "", "", "", "", "", "Handsome Character That Pass", "D13" ],
  [ "D15", "", "", "Original", "Do You Know That -Old School-", "BanYa Production", "120", "No exclusivity (NX2) WorldMax (NXA)", "3", "4", "15", "7", "18", "", "", "", "", "", "", "", "", "", "", "Do You Know That -Old School-", "D15" ],
  [ "D16", "", "", "Original", "Gun Rock", "BanYa Production", "104", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Gun Rock", "D16" ],
  [ "D17", "", "", "Original", "Bullfighter's Song", "BanYa Production", "168", "No exclusivity (NX2) WorldMax (NXA)", "4", "8", "16", "6", "20", "", "", "", "", "", "", "", "", "", "", "Bullfighter's Song", "D17" ],
  [ "D18", "", "", "Original", "Ugly Dee", "BanYa Production", "92", "Training Station (NX2) WorldMax (NX2, NXA)", "", "", "", "", "", "E4", "", "", "", "", "", "", "", "", "", "Ugly Dee", "D18" ],
  [ "D19", "", "", "K-Pop", "Hyun Jin Young Go Jin Young Go", "Hyun Jin Young", "150", "", "3", "6", "19", "6", "20", "", "", "", "", "", "", "", "", "", "", "Hyun Jin Young Go Jin Young Go", "D19" ],
  [ "D20", "", "", "K-Pop", "My Brother is Street Singer", "Park Hyang Lim vs. Yahpp", "129", "", "2", "5", "11", "3", "13", "", "", "", "", "", "", "", "", "", "", "My Brother is Street Singer", "D20" ],
  [ "D21", "", "", "K-Pop", "So", "Typhoon", "138", "No exclusivity (NX2) WorldMax (NXA)", "1", "6", "12", "2", "12", "", "", "", "", "", "", "", "", "", "", "So", "D21" ],
  [ "D22", "", "", "K-Pop", "Hold the Line", "Cho PD & B.E.G", "126", "", "2", "4", "12", "4", "14", "", "", "", "", "", "", "", "", "", "", "Hold the Line", "D22" ],
  [ "D23", "", "", "Pop", "Hybs", "DJ Dookie", "102", "", "2", "4", "11", "4", "13", "", "2", "4", "11", "4", "13", "", "", "", "", "Hybs", "D23" ],
  [ "D24", "", "", "Pop", "Throw 'em Up", "Andrew Kim", "100.2", "No exclusivity (NX2) Version 1.06 and older (NXA)", "2", "5", "14", "5", "15", "", "", "", "", "", "", "", "", "", "", "Throw 'em Up", "D24" ],
  [ "D25", "", "", "Pop", "Bust Back", "DVS", "94", "WorldMax (NX2)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Bust Back", "D25" ],
  [ "D26", "", "", "Pop", "Haley", "Sam-I-Am", "112", "", "2", "4", "9", "4", "11", "", "2", "4", "9", "4", "11", "", "", "", "", "Haley", "D26" ],
  [ "D27", "", "", "Pop", "We Goin' Fly Remix", "Gyfted", "112", "", "4", "5", "14", "6", "19", "", "3", "5", "15", "6", "19", "", "", "", "", "We Goin' Fly Remix", "D27" ],
  [ "D28", "", "", "Original", "Final Audition Episode 2-1", "Yahpp", "170", "", "3", "7", "20", "9", "22", "", "3", "7", "20", "9", "22", "", "", "", " Math", "Final Audition Episode 2-1", "D28" ],
  [ "D29", "", "", "Original", "Fire", "Yahpp", "136", "WorldMax (NX2)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Fire", "D29" ],
  [ "D30", "", "", "Original", "Final Audition Episode 2-2", "Yahpp", "200", "", "7", "16", "22", "18", "24", "", "7", "16", "22", "18", "24", "", "", "", "", "Final Audition Episode 2-2", "D30" ],
  [ "E01", "", "", "Original", "Solitary 1.5", "Yahpp", "136", "", "3", "7", "16", "6", "18", "", "4", "7", "16", "6", "18", "", "", "", "", "Solitary 1.5", "E01" ],
  [ "E02", "", "", "Original", "Beat the Ghost", "BanYa Production", "124", "No exclusivity (NX2) WorldMax (NXA)", "3", "9", "18", "7", "20", "", "", "", "", "", "", "", "", "", "", "Beat the Ghost", "E02" ],
  [ "E03", "", "", "Original", "Caprice of Otada", "BanYa Production", "160", "", "3", "8", "17", "9", "19", "", "3", "8", "17", "10", "18", "", "", "", " Obs.", "Caprice of Otada", "E03" ],
  [ "E04", "", "", "Original", "Money", "BanYa Production", "130", "No exclusivity (NX2) WorldMax (NXA)", "4", "7", "13", "8", "16", "", "", "", "", "", "", "", "", "", "", "Money", "E04" ],
  [ "E05", "", "", "Original", "Monkey Fingers 2", "BanYa Production", "180", "WorldMax (NX2, NXA) Brain Shower (NXA)", "4", "8", "17", "7", "19", "", "", "", "", "", "", "", "", "", " Mem.", "Monkey Fingers 2", "E05" ],
  [ "E06", "", "", "K-Pop", "Nice to Meet You", "Bae Chi Gi", "117", "", "2", "5", "14", "5", "14", "", "2", "5", "14", "5", "14", "", "", "", "", "Nice to Meet You", "E06" ],
  [ "E07", "", "", "K-Pop", "Very Old Couples", "015B", "121", "", "3", "6", "13", "6", "15", "", "2", "6", "13", "6", "15", "", "", "", " Mem.", "Very Old Couples", "E07" ],
  [ "E08", "", "", "K-Pop", "Get My Phone Call", "Mina", "113", "", "1", "5", "13", "5", "14", "E3", "1", "5", "13", "5", "14", "", "", "", "", "Get My Phone Call", "E08" ],
  [ "E09", "", "", "K-Pop", "Shiny Day", "Joanne", "106", "", "3", "5", "13", "4", "14", "E4", "3", "5", "13", "4", "14", "", "", "", "", "Shiny Day", "E09" ],
  [ "E10", "", "", "K-Pop", "A.U Ready?", "Gil Gun", "94", "", "2", "5", "10", "5", "12", "", "1", "5", "10", "5", "12", "", "", "", "", "A.U Ready?", "E10" ],
  [ "E11", "", "", "K-Pop", "V.I.P", "Bada", "112", "", "3", "5", "11", "5", "13", "", "3", "5", "11", "5", "15", "", "", "", "", "V.I.P", "E11" ],
  [ "E12", "", "", "Original", "Faster Z", "Yahpp", "162", "", "4", "11", "20", "15", "25", "", "4", "12", "19", "14", "20", "", "", "", "", "Faster Z", "E12" ],
  [ "E13", "", "", "Original", "Pumptris Quattro", "Yahpp", "153", "", "3", "8", "20", "14", "25", "", "3", "7", "19", "13", "20", "", "", "", " Math", "Pumptris Quattro", "E13" ],
  [ "E14", "", "", "K-Pop", "It's My Business", "Taiji Boys", "200", "", "3", "10", "20", "13", "21", "", "3", "11", "20", "13", "21", "", "", "", " Math", "It's My Business", "E14" ],
  [ "E15", "", "", "K-Pop", "You Fell in Me", "No Brain", "152", "", "2", "6", "17", "8", "16", "E9", "2", "6", "16", "8", "16", "", "", "", " Mem.", "You Fall in Me", "E15" ],
  [ "E16", "", "", "K-Pop", "Maelstrom", "Pia", "102", "", "3", "5", "16", "5", "18", "", "2", "5", "16", "5", "19", "", "", "", "", "A Maelstrom", "E16" ],
  [ "E17", "", "", "K-Pop", "Astral Song", "Crying Nut", "??? (~190)", "", "4", "9", "15", "9", "17", "", "3", "7", "15", "8", "17", "", "", "", "", "Astral Song", "E17" ],
  [ "E18", "", "", "K-Pop", "No Despair", "Hot Potato", "160", "", "1", "6", "18", "8", "20", "", "2", "6", "19", "8", "21", "", "", "", " Obs.", "No Despair", "E18" ],
  [ "E19", "", "", "K-Pop", "Compunction", "May", "133", "", "2", "6", "16", "4", "17", "E4", "2", "6", "16", "4", "17", "", "", "", " Obs.", "Compunction", "E19" ],
  [ "E20", "", "", "K-Pop", "Beat # No. 4", "HEaDTriP", "121", "", "2", "6", "16", "5", "17", "", "2", "6", "15", "5", "17", "", "", "", "", "Beat # No. 4", "E20" ],
  [ "E21", "", "", "K-Pop", "Come Back Home", "Taiji Boys", "93", "", "1", "4", "", "4", "", "E5", "1", "4", "", "4", "", "", "", "", " Mem.", "Come Back Home", "E21" ],
  [ "E22", "", "", "K-Pop", "Feel the Soul", "Seo Taiji", "93.54", "", "3", "9", "18", "4", "20", "", "2", "7", "17", "4", "18", "", "", "", " Math", "Feel the Soul", "E22" ],
  [ "E23", "", "", "Original", "Guitar Man", "BanYa Production", "120", "No exclusivity (NX2) WorldMax (NXA)", "3", "7", "12", "7", "13", "", "", "", "", "", "", "", "", "", "", "Guitar Man", "E23" ],
  [ "E24", "", "", "Original", "Higgledy Piggledy", "BanYa Production", "150", "", "2", "7", "15", "8", "17", "", "1", "6", "14", "8", "15", "", "", "", " Mem.", "Higgledy Piggledy", "E24" ],
  [ "E25", "", "", "Original", "Jam O Beat", "BanYa Production", "120", "", "3", "7", "15", "6", "16", "E5", "2", "7", "14", "6", "14", "", "", "", " Obs.", "Jam O Beat", "E25" ],
  [ "E26", "", "", "Pop", "Chopstix", "Sonic Dimension", "134", "", "3", "5", "14", "2", "16", "", "2", "5", "13", "2", "15", "", "", "", "", "Chopstix", "E26" ],
  [ "E27", "", "", "Pop", "Dance All Night", "Oscillator X", "140", "", "3", "6", "11", "6", "13", "", "2", "5", "13", "2", "15", "", "", "", " Obs.", "Dance All Night", "E27" ],
  [ "E28", "", "", "Pop", "Dance Vibrations", "Elpis", "130", "", "2", "6", "10", "6", "15", "E5", "1", "5", "10", "6", "15", "", "", "", "", "Dance Vibrations", "E28" ],
  [ "E29", "", "", "Pop", "Energizer", "ZiGZaG", "151.5", "", "3", "9", "16", "10", "17", "", "2", "9", "16", "11", "17", "", "", "", "", "Energizer", "E29" ],
  [ "E30", "", "", "Pop", "Groovin' Motion", "Sonic Dimension", "130.02", "", "3", "6", "12", "6", "12", "", "3", "6", "9", "6", "11", "", "", "", "", "Groovin' Motion", "E30" ],
  [ "E31", "", "", "K-Pop", "Tell Me", "Wonder Girls", "127", "Korean version (NX2) No exclusivity (NXA)", "2", "5", "14", "5", "16", "", "1", "5", "12", "5", "14", "", "", "", "", "Tell Me", "E31" ],
  [ "E92", "", "", "Pop", "Fist of Fury", "Luo Zi Xiang", "92", "Chinese version (NX2) Easy Station (NXA)", "1", "6", "11", "4", "15", "E5", "", "", "", "", "", "", "", "", "", "Fist of Fury", "E92" ],
  [ "E93", "", "", "Pop", "Long Live the Chinese", "Wang Lee Hom", "140", "Chinese version (NX2) Easy Station (NXA)", "2", "6", "10", "4", "15", "E6", "", "", "", "", "", "", "", "", "", "Long Live the Chinese", "E93" ],
  [ "E94", "", "", "Pop", "Fire", "Karen Mok", "125", "Chinese version (NX2)", "2", "6", "11", "3", "14", "", "", "", "", "", "", "", "", "", "", "Fire", "E94" ],
  [ "E95", "", "", "Pop", "Wild Game", "Jolin Tsai", "139", "Chinese version (NX2)", "3", "6", "13", "4", "15", "", "", "", "", "", "", "", "", "", "", "Wild Game", "E95" ],
  [ "E96", "", "", "Pop", "One Last Chance", "ENERGY", "100", "Chinese version (NX2)", "1", "4", "11", "3", "10", "", "", "", "", "", "", "", "", "", "", "One Last Chance", "E96" ],
  [ "E97", "", "", "Pop", "Mechanical Doll", "Luo Zi Xiang", "106", "Chinese version (NX2)", "4", "4", "10", "4", "11", "", "", "", "", "", "", "", "", "", "", "Mechanical Doll", "E97" ],
  [ "E99", "", "", "Pop", "Take It Off", "Alex", "132", "Chinese version (NX2)", "3", "6", "10", "4", "17", "", "", "", "", "", "", "", "", "", "", "Take It Off", "E99" ],
  [ "F01", "", "", "Original", "Blaze Emotion", "Yahpp", "170", "", "", "", "", "", "", "E3", "2", "7", "17", "10", "18", "", "", "", " Obs.", "Blaze Emotion", "F01" ],
  [ "F02", "", "", "Original", "Cannon X.1", "Yahpp", "185", "", "", "", "", "", "", "", "3", "10", "20", "13", "23", "", "", "", " Math", "Cannon X.1", "F02" ],
  [ "F03", "", "", "Original", "Chopsticks Challenge", "Yahpp", "128", "", "", "", "", "", "", "", "1", "6", "17", "3", "16", "", "", "", " Obs.", "Chopsticks Challenge", "F03" ],
  [ "F04", "", "", "K-Pop", "LaLaLa", "Big Bang", "102", "", "", "", "", "", "", "", "2", "5", "10", "5", "13", "", "", "", " Mem.", "LaLaLa", "F04" ],
  [ "F05", "", "", "K-Pop", "Adios", "Eun Ji Won", "123", "", "", "", "", "", "", "", "2", "6", "14", "4", "16", "", "", "", " Math", "Adios", "F05" ],
  [ "F06", "", "", "K-Pop", "Slightly", "45RPM", "120", "", "", "", "", "", "", "", "1", "4", "14", "5", "12", "", "", "", " Obs.", "Slightly", "F06" ],
  [ "F07", "", "", "K-Pop", "I'm Your Girl", "S.E.S", "101.814", "", "", "", "", "", "", "E4", "2", "5", "12", "6", "10", "", "", "", "", "I Am Your Girl", "F07" ],
  [ "F08", "", "", "K-Pop", "Only You", "Namolla Family", "108", "", "", "", "", "", "", "E4", "3", "6", "12", "3", "13", "", "", "", "", "Only You", "F08" ],
  [ "F09", "", "", "K-Pop", "Chocolate", "Banana Girl", "130", "", "", "", "", "", "", "E6", "2", "5", "9", "3", "9", "", "", "", "", "Chocolate", "F09" ],
  [ "F10", "", "", "Pop", "Forward", "DJ Missill", "97/194", "", "", "", "", "", "", "", "2", "5", "13", "5", "13", "", "", "", "", "Forward", "F10" ],
  [ "F11", "", "", "Pop", "Uprock", "Sam-I-Am", "120", "", "", "", "", "", "", "", "2", "5", "17", "4", "14", "", "", "", " Mem.", "Uprock", "F11" ],
  [ "F12", "", "", "Pop", "Crazy", "Gyfted", "108.095", "", "", "", "", "", "", "E6", "2", "5", "15", "6", "19", "", "", "", " Obs.", "Crazy", "F12" ],
  [ "F13", "", "", "Pop", "Panuelito Rojo", "Big Metra", "98/196", "", "", "", "", "", "", "E5", "1", "5", "10", "4", "18", "", "", "", " Obs.", "Panuelito Rojo", "F13" ],
  [ "F14", "", "", "Pop", "Procedimientos Para Llegar A Un Comun Acuerdo", "Pxndx", "160", "", "", "", "", "", "", "E5", "3", "7", "15", "7", "16", "", "", "", " Math", "Procedimientos Para Llegar A Un Comun Acuerdo", "F14" ],
  [ "F15", "", "", "Pop", "Digan Lo Que Digan", "Nina Pilots", "162", "", "", "", "", "", "", "E6", "3", "6", "16", "8", "13", "", "", "", " Obs.", "Digan Lo Que Digan", "F15" ],
  [ "F16", "", "", "Pop", "Pump Breakers", "Tico", "120/240", "", "", "", "", "", "", "", "2", "5", "17", "4", "15", "", "", "", " Math", "Pump Breakers", "F16" ],
  [ "F17", "", "", "Pop", "Change Myself", "Wang Lee Hom", "104", "", "", "", "", "", "", "", "1", "5", "10", "5", "9", "", "", "", "", "Change Myself", "F17" ],
  [ "F18", "", "", "K-Pop", "Come On!", "Lee Jeong Hyun", "140", "", "", "", "", "", "", "E5", "2", "5", "12", "4", "9", "", "", "", "", "Come On!", "F18" ],
  [ "F19", "", "", "K-Pop", "Bad Character", "Jang Na Ra", "100", "", "", "", "", "", "", "", "1", "6", "10", "3", "11", "", "", "", "", "Bad Character", "F19" ],
  [ "F20", "", "", "K-Pop", "U", "Super Junior M", "115", "", "", "", "", "", "", "E5", "2", "6", "14", "5", "13", "", "", "", "", "U", "F20" ],
  [ "F21", "", "", "K-Pop", "Breakin' Love", "Yoo Seung Jun", "102", "", "", "", "", "", "", "", "2", "6", "12", "4", "14", "", "", "", "", "Breakin' Love", "F21" ],
  [ "F22", "", "", "Original", "The People Didn't Know", "BanYa Production", "134", "", "", "", "", "", "", "", "2", "5", "15", "7", "17", "", "", "", " Mem.", "The People Didn't Know", "F22" ],
  [ "F23", "", "", "Original", "DJ Otada", "BanYa Production", "180", "", "", "", "", "", "", "", "4", "8", "19", "14", "22", "", "", "", " Obs.", "DJ Otada", "F23" ],
  [ "F24", "", "", "Original", "K.O.A. -Alice in Wonderworld-", "BanYa Production", "156", "", "", "", "", "", "", "", "3", "8", "17", "9", "18", "", "", "", " Obs.", "K.O.A ~Alice in Wonderland~", "F24" ],
  [ "F25", "", "", "Original", "My Dreams", "BanYa Production", "136", "", "", "", "", "", "", "", "4", "10", "18", "5", "18", "", "", "", "", "My Dreams", "F25" ],
  [ "F26", "", "", "Original", "Toccata", "BanYa Production", "104", "", "", "", "", "", "", "", "3", "10", "17", "6", "14", "", "", "", " Math", "Toccata", "F26" ],
  [ "F27", "", "", "K-Pop", "Do It!", "House Rulez", "129", "2009 event", "", "", "", "", "", "", "2", "6", "15", "4", "18", "", "", "", "", "Do It!", "F27" ],
  [ "F28", "", "", "K-Pop", "Dawn of the Apocalypse", "Vassline", "??", "2009 event", "", "", "", "", "", "", "4", "14", "21", "14", "21", "", "", "", "", "Dawn of the Apocalypse", "F28" ],
  [ "F29", "", "", "Original", "Final Audition Episode 2-X", "Yahpp", "170", "2009 event", "", "", "", "", "", "", "8", "17", "25", "21", "25", "", "", "", "", "Final Audition Episode 2-X", "F29" ],
  //[ "F80", "", "", "K-Pop", "My Fantasy (MV Ver.)", "Taiji Boys", "130", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "My Fantasy (MV Ver.)", "F80" ],
];
//  [ "ID#", "NX2", "NXA", "Channel", "Song Title", "Artist", "BPM", "Exclusivity", "NL", "HD", "CZ", "FS", "NM", "E", "NL", "HD", "CZ", "FS", "NM", "Training Station (NX2)", "WorldMax (NX2)", "WorldMax (NXA)", "Brain Shower (NXA)", "Song Title", "ID" ],

AddCheckTracklist( test_PH_NX2_NXA_tracklist, test_PH_NX2_NXA_arcade, { channel: 3, title: 4, artist: 5, bpm: 6, NX2: 8, NXA: 14, } );

var test_PH_NX2_NXA_special = 
[
  [ "D31", "", "", "Special", "K-Pop Dance Remix", "DJ. DOC/Epik High", "132", "", "", "8", "15", "9", "17", "", "", "", "", "", "", "", "", "", "K-Pop Dance Remix", "D31" ],
  [ "D32", "", "", "Special", "Groove Party Remix", "Clon/Tashannie", "105-110", "", "", "7", "13", "6", "15", "", "5", "14", "5", "15", "", "", "", "", "Groove Party Remix", "D32" ],
  [ "D33", "", "", "Special", "Pop House Remix", "Kristeen/Scoop/Fresno", "126-130.5", "", "", "8", "15", "", "16", "", "", "", "", "", "", "", "", "", "Pop House Remix", "D33" ],
  [ "D34", "", "", "Special", "Wi-Ex Doc-Va", "Yahpp", "195", "", "", "16", "21", "19", "25", "", "15", "21", "15", "23", "", "", "", "", "Wi-Ex Doc-Va Remix", "D34" ],
  [ "D35", "", "", "Special", "Bemera", "Yahpp", "210", "", "", "15", "24", "18", "25", "", "16", "24", "18", "25", "", "", "", "", "Bemera Remix", "D35" ],
  [ "D36", "", "", "Special", "BanYa-P Classic Mix", "BanYa Production", "92-180", "", "", "14", "19", "15", "20", "", "", "", "", "", "", "", "", "", "BanYa-P Classic Mix", "D36" ],
  [ "D37", "", "", "Special", "Chicago Club Mix", "Haley/DVS/Gyfted", "112", "WorldMax (NX2)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Chicago Club Mix", "D37" ],
  [ "D38", "", "", "Special", "U Inside My Dim Memory  [FULL]", "Hyun Jin Young vs. Yahpp", "118", "WorldMax (NX2, NXA beta version)", "", "9", "15", "10", "19", "", "", "", "", "", "", "", "", "", "U Inside My Dim Memory  [FULL]", "D38" ],
  [ "D39", "", "", "Special", "Fire  [FULL]", "Yahpp", "136", "", "", "", "19", "", "20", "", "", "", "", "", "", "", "", "", "Fire  [FULL]", "D39" ],
  [ "D40", "", "", "Special", "Lovely  [FULL]", "Kim Jong Kook", "188", "", "", "6", "", "7", "", "", "", "", "", "", "", "", "", "", "Lovely  [FULL]", "D40" ],
  [ "D41", "", "", "Special", "Love is a Danger Zone 2  [FULL]", "Yahpp", "100-162", "", "", "", "19", "", "21", "", "", "19", "", "21", "", "", "", "", "Love is a Danger Zone 2  [FULL]", "D41" ],
  [ "D42", "", "", "Special", "Beat of the War 2  [FULL]", "Yahpp", "190-??", "", "", "", "19", "", "21", "", "", "19", "", "20", "", "", "", "", "Beat of the War 2  [FULL]", "D42" ],
  [ "D43", "", "", "Special", "Hold the Line  [FULL]", "Cho PD & B.E.G", "126", "", "", "7", "16", "8", "18", "", "", "", "", "", "", "", "", "", "Hold the Line  [FULL]", "D43" ],
  [ "DB26", "", "", "Special", "Novarash", "Novasonic/Crash", "118", "", "", "8", "16", "10", "", "", "", "", "", "", "", "", "", "", "Novarash Remix", "DB26" ],
  [ "DB28", "", "", "Special", "Treme-Vook of the War", "BanYa", "140-202", "", "", "13", "19", "16", "22", "", "12", "18", "15", "22", "", "", "", "", "Treme-Vook of the War Remix", "DB28" ],
  [ "DB29", "", "", "Special", "BanYa Classic Remix", "BanYa", "162", "No exclusivity (NX2) WorldMax (NXA)", "", "10", "19", "11", "21", "", "", "", "", "", "", "", "", "", "BanYa Classic Mix", "DB29" ],
  [ "DB30", "", "", "Special", "Deux Remix", "Deux", "119.5", "", "", "7", "14", "8", "", "", "", "", "", "", "", "", "", "", "Deux Remix", "DB30" ],
  [ "DB51", "", "", "Special", "Dignity  [FULL]", "Crash", "195", "", "", "13", "20", "16", "22", "", "14", "19", "16", "22", "", "", "", "", "Dignity  [FULL]", "DB51" ],
  [ "DB53", "", "", "Special", "Turbo Remix", "Turbo", "147.7", "", "", "9", "12", "10", "", "", "", "", "", "", "", "", "", "", "Turbo Remix", "DB53" ],
  [ "DB54", "", "", "Special", "2nd Hidden Remix", "CLON/Sechskies", "140", "", "", "10", "11", "13", "16", "", "", "", "", "", "", "", "", "", "2nd Hidden Remix", "DB54" ],
  [ "DB55", "", "", "Special", "Drunken Family Remix", "Drunken Tiger/Honey Family", "95", "", "", "6", "7", "6", "", "", "", "", "", "", "", "", "", "", "Drunken Family Remix", "DB55" ],
  [ "DB56", "", "", "Special", "BanYa Hip-Hop Remix", "BanYa", "99", "", "", "7", "8", "7", "", "", "3", "9", "7", "", "", "", "", "", "BanYa Hip-Hop Remix", "DB56" ],
  [ "DB57", "", "", "Special", "Canon-D  [FULL]", "BanYa", "160", "", "", "15", "17", "", "", "", "11", "16", "", "", "", "", "", "", "Canon-D  [FULL]", "DB57" ],
  [ "DC41", "", "", "Special", "Love is a Danger Zone (try to B.P.M.)", "BanYa", "140-168", "", "", "14", "21", "16", "23", "", "15", "19", "15", "22", "", "", "", "", "Try to B.P.M - LIADZ Remix", "DC41" ],
  [ "DC42", "", "", "Special", "Zero K-Hip Hop Remix", "Drunken Tiger/JTL/Perry/Eun Ji Won", "110", "", "", "8", "14", "7", "", "", "", "", "", "", "", "", "", "", "Zero K-Hip Hop Remix", "DC42" ],
  [ "E50", "", "", "Special", "BanYa-P Guitar Remix", "BanYa Production", "120", "", "", "", "25", "", "25", "", "", "22", "", "24", "", "", "", "", "BanYa-P Guitar Remix", "E50" ],
  [ "E51", "", "", "Special", "Guitar Man  [FULL]", "BanYa Production", "120", "No exclusivity (NX2) WorldMax (NXA)", "", "8", "", "9", "", "", "", "", "", "", "", "", "", "", "Guitar Man  [FULL]", "E51" ],
  [ "E52", "", "", "Special", "Money Fingers", "BanYa Production", "170", "", "", "9", "14", "10", "18", "", "", "", "", "", "", "", "", "", "Money Fingers", "E52" ],
  [ "E53", "", "", "Special", "Monkey Fingers  [FULL]", "BanYa Production", "186", "", "5", "9", "17", "7", "19", "", "8", "16", "9", "17", "", "", "", "", "Monkey Fingers  [FULL]", "E53" ],
  [ "E54", "", "", "Special", "NX2 K-Pop Remix 1", "U;Nee/Duke/Lee Hyun Do", "136", "", "", "8", "15", "9", "16", "", "6", "13", "7", "16", "", "", "", "", "NX2 K-Pop Remix 1", "E54" ],
  [ "E55", "", "", "Special", "NX2 K-Hip Hop Remix", "Eun Ji Won/Dynamic Duo", "110", "", "", "7", "14", "", "15", "", "", "", "", "", "", "", "", "", "NX2 K-Hip Hop Remix", "E55" ],
  [ "E56", "", "", "Special", "Astral Song  [FULL]", "Crying Nut", "??? (~190)", "", "", "8", "", "", "", "", "", "", "", "", "", "", "", "", "Astral Song  [FULL]", "E56" ],
  [ "E57", "", "", "Special", "NX2 K-Pop Remix 2", "Mina/Bae Chi Gi", "117", "", "", "7", "", "", "14", "", "5", "", "", "15", "", "", "", "", "NX2 K-Pop Remix 2", "E57" ],
  [ "E58", "", "", "Special", "No Despair  [FULL]", "Hot Potato", "160", "", "", "7", "18", "", "20", "", "", "", "", "", "", "", "", "", "No Despair  [FULL]", "E58" ],
  [ "E59", "", "", "Special", "NX2 K-Pop Remix 3", "Lee Hyun Do/Som 2", "112", "", "", "7", "13", "", "13", "", "", "", "", "", "", "", "", "", "NX2 K-Pop Remix 3", "E59" ],
  [ "E60", "", "", "Special", "NX2 Diva Remix", "Joanne/Bada", "120", "", "", "4", "12", "5", "", "", "4", "9", "5", "", "", "", "", "", "NX2 Diva Remix", "E60" ],
  //[ "E61", "", "", "Special", "Pro Pop Remix", "Sonic Dimension / Oscillator X", "140", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Pro Pop Remix", "E61" ],
  //[ "E63", "", "", "Special", "May Remix", "May", "128", "WorldMax (NX2)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "May Remix", "E63" ],
  //[ "E64", "", "", "Special", "Red Song", "??", "240", "WorldMax (NX2)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Red Song Remix", "E64" ],
  [ "E70", "", "", "Special", "It's My Business  [FULL]", "Taiji Boys", "200", "No exclusivity (NX2) WorldMax (NXA)", "", "8", "19", "", "20", "", "", "", "", "", "", "", "", "", "It's My Business  [FULL]", "E70" ],
  [ "E71", "", "", "Special", "Very Old Couples  [FULL]", "015B", "121", "", "", "6", "14", "", "", "", "", "", "", "", "", "", "", "", "Very Old Couples  [FULL]", "E71" ],
  [ "E72", "", "", "Special", "Come Back Home  [FULL]", "Taiji Boys", "93", "", "1", "4", "", "4", "", "1", "3", "", "4", "", "", "", "", "", "Come Back Home  [FULL]", "E72" ],
  [ "E73", "", "", "Special", "Feel the Soul  [FULL]", "Seo Taiji", "187.08", "No exclusivity (NX2) WorldMax (NXA)", "", "", "18", "", "", "", "", "", "", "", "", "", "", "", "Feel the Soul  [FULL]", "E73" ],
  [ "E74", "", "", "Special", "V.I.P  [FULL]", "Bada", "112", "", "2", "6", "", "6", "", "1", "4", "", "4", "", "", "", "", "", "V.I.P  [FULL]", "E74" ],
  //[ "E75", "", "", "Special", "Maelstrom  [FULL]", "Pia", "102", "WorldMax (NX2, NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "A Maelstrom  [FULL]", "E75" ],
  [ "E76", "", "", "Special", "Fly  [FULL]", "Epik High", "128", "", "", "10", "15", "", "17", "", "", "", "", "", "", "", "", "", "Fly  [FULL]", "E76" ],
  [ "E77", "", "", "Special", "Tell Me  [FULL]", "Wonder Girls", "127", "Korean version (NX2) No exclusivity (NXA)", "", "5", "", "5", "", "", "2", "", "3", "", "", "", "", "", "Tell Me  [FULL]", "E77" ],
  [ "E928", "", "", "Special", "FAE1 & Chicken Wing Remix (NX2 ver.)", "BanYa", "200", "", "", "10", "", "11", "", "", "8", "21", "13", "", "", "", "", "", "FAE1 & Chicken Wing Remix (NX2 ver.)", "E928" ],
  [ "F30", "", "", "Special", "45rpm & Eun Ji Won Remix", "45RPM / Eun Ji Won", "123", "", "", "", "", "", "", "", "", "11", "5", "14", "", "", "", "", "45rpm & Eun Ji Won Remix", "F30" ],
  [ "F31", "", "", "Special", "The People Didn't Know \"Pumping Up\"", "BanYa Production", "134", "", "", "", "", "", "", "", "7", "", "4", "17", "", "", "", "", "The People Didn't Know &quot;Pumping Up&quot;", "F31" ],
  [ "F32", "", "", "Special", "Ugly Duck Toccata", "BanYa Production", "104", "", "", "", "", "", "", "", "12", "15", "", "16", "", "", "", "", "Ugly Duck Toccata", "F32" ],
  [ "F33", "", "", "Special", "Caprice of DJ Otada", "BanYa Production", "180", "", "", "", "", "", "", "", "11", "19", "", "22", "", "", "", "", "Caprice of DJ Otada", "F33" ],
  [ "F34", "", "", "Special", "Dr. K.O.A", "BanYa Production", "156", "", "", "", "", "", "", "", "8", "18", "", "20", "", "", "", "", "Dr. K.O.A", "F34" ],
  [ "F35", "", "", "Special", "Jam O Beat # No. 4", "BanYa Production / HEaDTriP", "121", "", "", "", "", "", "", "", "", "16", "6", "16", "", "", "", "", "Jam O Beat # No. 4", "F35" ],
  [ "F36", "", "", "Special", "YG Remix", "Big Bang / Perry", "102", "", "", "", "", "", "", "", "5", "", "6", "15", "", "", "", "", "YG Remix", "F36" ],
  [ "F37", "", "", "Special", "Nina Pxndx Mix", "Nina Pilots / Pxndx", "160", "", "", "", "", "", "", "", "6", "16", "8", "", "", "", "", "", "Nina Pxndx Remix", "F37" ],
  [ "F38", "", "", "Special", "Big Metra Remix", "Big Metra", "105", "", "", "", "", "", "", "", "5", "19", "", "17", "", "", "", "", "Big Metra Remix", "F38" ],
  [ "F39", "", "", "Special", "NXA Hip-Hop Mix", "DJ Missill / Gyfted", "108", "", "", "", "", "", "", "", "6", "13", "4", "", "", "", "", "", "NXA Hip-Hop Mix", "F39" ],
  [ "F40", "", "", "Special", "Novasonic Mix ver. 3", "Novasonic", "136", "", "", "", "", "", "", "", "6", "17", "", "19", "", "", "", "", "Novasonic Mix ver. 3", "F40" ],
  [ "F41", "", "", "Special", "Mr. Fire Fighter Falls in Love With Me", "Spooky Banana / No Brain", "158", "", "", "", "", "", "", "", "8", "15", "9", "", "", "", "", "", "Mr. Fire Fighter Falls in Love With Me", "F41" ],
  [ "F42", "", "", "Special", "J Knows That Old Bong", "BanYa Production", "130", "", "", "", "", "", "", "", "8", "17", "", "18", "", "", "", "", "J Knows That Old Bong", "F42" ],
  [ "F43", "", "", "Special", "Turkey Virus", "BanYa Production", "150-162", "", "", "", "", "", "", "", "8", "15", "11", "", "", "", "", "", "Turkey Virus", "F43" ],
  [ "F44", "", "", "Special", "msgoon RMX pt. 1", "msgoon", "120", "", "", "", "", "", "", "", "7", "17", "", "17", "", "", "", "", "msgoon RMX pt. 1", "F44" ],
  [ "F45", "", "", "Special", "msgoon RMX pt. 2", "msgoon", "105", "", "", "", "", "", "", "", "5", "16", "5", "", "", "", "", "", "msgoon RMX pt. 2", "F45" ],
  [ "F46", "", "", "Special", "msgoon RMX pt. 3", "msgoon", "168", "", "", "", "", "", "", "", "6", "17", "11", "20", "", "", "", "", "msgoon RMX pt. 3", "F46" ],
  [ "F50", "", "", "Special", "Chopsticks Challenge  [FULL]", "Yahpp", "128", "", "", "", "", "", "", "", "", "15", "3", "19", "", "", "", "", "Chopsticks Challenge  [FULL]", "F50" ],
  [ "F51", "", "", "Special", "LaLaLa  [FULL]", "Big Bang", "102", "", "", "", "", "", "", "", "4", "14", "4", "", "", "", "", "", "LaLaLa  [FULL]", "F51" ],
  [ "F52", "", "", "Special", "Adios  [FULL]", "Eun Ji Won", "123", "", "", "", "", "", "", "", "4", "15", "4", "", "", "", "", "", "Adios  [FULL]", "F52" ],
  [ "F53", "", "", "Special", "Panuelito Rojo  [FULL]", "Big Metra", "98", "", "", "", "", "", "", "", "9", "16", "", "18", "", "", "", "", "Panuelito Rojo  [FULL]", "F53" ],
  [ "F54", "", "", "Special", "Procedimientos Para Llegar A Un Comun Acuerdo  [FULL]", "Pxndx", "160", "", "", "", "", "", "", "", "6", "17", "7", "", "", "", "", "", "Procedimientos Para Llegar A Un Comun Acuerdo  [FULL]", "F54" ],
  [ "F55", "", "", "Special", "Forward  [FULL]", "DJ Missill", "97", "", "", "", "", "", "", "", "4", "15", "5", "", "", "", "", "", "Forward  [FULL]", "F55" ],
  [ "F56", "", "", "Special", "Slightly  [FULL]", "45rpm ft. msgoon", "120", "", "", "", "", "", "", "", "5", "17", "5", "", "", "", "", "", "Slightly  [FULL]", "F56" ],
  [ "F57", "", "", "Special", "Come On!  [FULL]", "Lee Jeong Hyun", "140", "", "", "", "", "", "", "", "6", "", "6", "", "", "", "", "", "Come On!  [FULL]", "F57" ],
  [ "F58", "", "", "Special", "Chocolate  [FULL]", "Banana Girl", "130", "", "", "", "", "", "", "", "6", "15", "8", "", "", "", "", "", "Chocolate  [FULL]", "F58" ],
  [ "F59", "", "", "Special", "Digan Lo Que Digan  [FULL]", "Nina Pilots", "162", "", "", "", "", "", "", "", "7", "18", "9", "", "", "", "", "", "Digan Lo Que Digan  [FULL]", "F59" ],
  [ "F60", "", "", "Special", "Trato De No Trabarme  [FULL]", "Big Metra", "105", "2009 event", "", "", "", "", "", "", "10", "23", "", "25", "", "", "", "", "Trato De No Trabarme  [FULL]", "F60" ],
  [ "F61", "", "", "Special", "Crazy  [FULL]", "Gyfted", "108.1", "", "", "", "", "", "", "", "3", "13", "3", "", "", "", "", "", "Crazy  [FULL]", "F61" ],
  [ "F62", "", "", "Special", "U  [FULL]", "Super Junior M", "115", "", "", "", "", "", "", "", "3", "15", "3", "", "", "", "", "", "U  [FULL]", "F62" ],
  [ "F63", "", "", "Special", "Change Myself  [FULL]", "Wang Lee Hom", "104.5", "", "", "", "", "", "", "", "3", "14", "3", "", "", "", "", "", "Change Myself  [FULL]", "F63" ],
  [ "F64", "", "", "Special", "Enter the Dragon  [FULL]", "JTL", "110", "", "", "", "", "", "", "", "", "17", "3", "18", "", "", "", "", "Enter the Dragon  [FULL]", "F64" ],
  [ "F65", "", "", "Special", "Beat # No. 4  [FULL]", "HEaDTriP", "121", "", "", "", "", "", "", "", "", "17", "6", "19", "", "", "", "", "Beat # No. 4  [FULL]", "F65" ],
  //[ "F70", "", "", "Special", "Yasangma 2", "BanYa Production", "180", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" ],
  //[ "F71", "", "", "Special", "Scream Song", "msgoon", "??", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" ],
  //[ "F72", "", "", "Special", "msgoon RMX pt. 4", "msgoon", "128", "WorldMax (NXA)", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" ],


  //[ "ID#", "NX2", "NXA", "Channel", "Song Title", "Artist", "BPM", "Exclusivity", "NL", "HD", "CZ", "FS", "NM", "NL", "HD", "CZ", "FS", "NM", "Training Station (NX2)", "WorldMax (NX2)", "WorldMax (NXA)", "Brain Shower (NXA)", "Song Title", "ID" ],

/*
  [ "B06F", "", "", "Special", "Deja Vu  [FULL]", "Som2", "115", "WorldMax (NX2, NXA)", "", "", "", "", "Deja Vu  [FULL]", "B06F" ],
  [ "B09F", "", "", "Special", "Typhoon  [FULL]", "Lee Hyun Do", "112", "WorldMax (NX2, NXA)", "", "", "", "", "Typhoon  [FULL]", "B09F" ],
  [ "B13F", "", "", "Special", "I'll Give You All My Love  [FULL]", "WAX", "164", "WorldMax (NX2, NXA)", "", "", "", "", "I'll Give You All My Love  [FULL]", "B13F" ],
  [ "B27", "", "", "Special", "Lexy/1TYM Remix", "Lexy / 1TYM", "123", "WorldMax (NX2, NXA)", "", "", "", "", "Lexy/1TYM Remix", "B27" ],
  [ "B52", "", "", "Special", "Novasonic Remix", "Novasonic", "136", "WorldMax (NX2)", "", "", "", "", "Novasonic Remix", "B52" ],
  [ "C02A", "", "", "Special", "Moonlight (Original Ver.)", "BanYa", "180", "WorldMax (NX2, NXA)", "", "", "", "", "Moonlight (alternate version)", "C02A" ],
  [ "C03A", "", "", "Special", "Witch Doctor (Witch Docva version)", "Yahpp", "195", "WorldMax (NX2, NXA)", "", "", "", "", "Witch Doctor (Witch Docva version)", "C03A" ],
  [ "C05A", "", "", "Special", "Phantom (Speedup Ver.)", "BanYa Production", "??", "Training Station (NX2) WorldMax (NXA)", "", "", "", "", "Phantom (Speedup Ver.)", "C05A" ],
  [ "C08F", "", "", "Special", "Emergency  [FULL]", "Drunken Tiger", "110", "WorldMax (NX2)", "", "", "", "", "Emergency  [FULL]", "C08F" ],
  [ "C15F", "", "", "Special", "Mr. Fire Fighter  [FULL]", "Spooky Banana", "158", "WorldMax (NX2, NXA)", "", "", "", "", "Mr. Fire Fighter  [FULL]", "C15F" ],
  [ "C1C01", "", "", "Special", "Beat of the War (D&G version)", "Yahpp", "190/140/120/160", "WorldMax (NX2, NXA)", "", "", "", "", "Beat of the War (D&G version)", "C1C01" ],
  [ "C1C04", "", "", "Special", "Love is a Danger Zone 2 (D&G version)", "Yahpp", "162", "WorldMax (NX2, NXA) Brain Shower (NXA)", "", "", "", "", "Love is a Danger Zone 2 (D&G version)", "C1C04" ],
  [ "D08F", "", "", "Special", "Free!  [FULL]", "Jiny", "174.6", "WorldMax (NX2)", "", "", "", "", "Free  [FULL]", "D08F" ],
  [ "D11F", "", "", "Special", "For You  [FULL]", "N.Ex.T", "160", "WorldMax (NX2, NXA beta version)", "", "", "", "", "For You  [FULL]", "D11F" ],
  [ "E07A", "", "", "Special", "Very Old Couples (Short Term Memory version)", "015B", "121", "WorldMax (NX2, NXA)", "", "", "", "", "Very Old Couples (Short Term Memory version)", "E07A" ],
  [ "E10F", "", "", "Special", "A.U Ready?  [FULL]", "Gil Gun", "94", "WorldMax (NX2, NXA)", "", "", "", "", "A.U Ready?  [FULL]", "E10F" ],
  [ "E13B", "", "", "Special", "Pumptris Quattro (8bit version)", "Yahpp", "162", "WorldMax (NX2) No exclusivity (NXA)", "", "", "", "", "Pumptris Quattro (8bit version)", "E13B" ],
  [ "E15F", "", "", "Special", "You Fall in Me  [FULL]", "No Brain", "152", "WorldMax (NX2, NXA)", "", "", "", "", "You Fall in Me  [FULL]", "E15F" ],
  [ "E17A", "", "", "Special", "Astral Song (alternate version)", "Crying Nut", "??? (~190)", "WorldMax (NX2, NXA)", "", "", "", "", "Astral Song (alternate version)", "E17A" ],
  [ "E18A", "", "", "Special", "No Despair (alternate version)", "Hot Potato", "160", "WorldMax (NX2, NXA)", "", "", "", "", "No Despair (alternate version)", "E18A" ],
  [ "E20A", "", "", "Special", "Beat # No. 4 (alternate version)", "HEaDTriP", "121", "WorldMax (NX2, NXA)", "", "", "", "", "Beat # No. 4 (alternate version)", "E20A" ],
  [ "E20F", "", "", "Special", "Beat # No. 4  [FULL]", "HEaDTriP", "121", "WorldMax (NX2, NXA)", "", "", "", "", "Beat # No. 4  [FULL]", "E20F" ],
  [ "EF175", "", "", "Special", "Final Audition 3 (Unfinished ver.)", "Yahpp", "130.5/210", "WorldMax (NX2, NXA)", "", "", "", "", "Final Audition 3 (Unfinished ver.)", "EF175" ],
  [ "EF282", "", "", "Special", "Yasangma", "Yahpp", "??", "WorldMax (NX2, NXA)", "", "", "", "", "Yasangma", "EF282" ],
  [ "EF921", "", "", "Special", "Mr. Fire Fighter & Beat of the War 2", "Spooky Banana / Yahpp", "158/190/140/120/160", "WorldMax (NX2, NXA)", "", "", "", "", "Mr. Fire Fighter & Beat of the War 2", "EF921" ],
*/

  [ "D112", "", "", "Special", "Another Truth (Another)", "Novasonic", "136", "", "", "", "", "18", "21", "", "", "", "17", "22", "", "", "", "", "Another Truth (Another)", "D112" ],
  [ "D204", "", "", "Special", "Final Audition (Another)", "BanYa", "130.5", "", "", "", "17", "", "16", "", "", "15", "", "16", "", "", "", "", "Final Audtion (Another)", "D204" ],
  [ "D205", "", "", "Special", "Extravaganza (Another)", "BanYa", "195", "", "", "", "21", "", "19", "", "16", "21", "", "19", "", "", "", "", "Extravaganza (Another)", "D205" ],
  [ "D301", "", "", "Special", "Final Audition 2 (Another)", "BanYa", "130", "", "", "", "16", "", "19", "", "", "16", "", "19", "", "", "", "", "Final Audition 2 (Another)", "D301" ],
  [ "D405", "", "", "Special", "Mr. Larpus (Another)", "BanYa", "190", "", "", "", "21", "23", "25", "", "", "22", "23", "25", "", "", "", "", "Mr. Larpus (Another)", "D405" ],
  [ "D505", "", "", "Special", "Beethoven Virus (Another)", "BanYa", "162", "", "", "7", "17", "9", "", "", "10", "17", "11", "", "", "", "", "", "Beethoven Virus (Another)", "D505" ],
  [ "D701", "", "", "Special", "Dr. M (Another)", "BanYa", "145", "", "", "", "16", "", "", "", "", "16", "", "", "", "", "", "", "Dr. M (Another)", "D701" ],
  [ "D704", "", "", "Special", "Love is a Danger Zone (Another)", "BanYa", "140", "", "", "", "16", "8", "??", "", "", "16", "7", "??", "", "", "", "", "Love is a Danger Zone (Another)", "D704" ],
  [ "D735", "", "", "Special", "Vook (Another)", "BanYa", "184", "", "", "16", "18", "12", "19", "", "17", "20", "12", "19", "", "", "", "", "Vook (Another)", "D735" ],
  [ "D802", "", "", "Special", "Bee (Another)", "BanYa", "160", "", "", "", "18", "", "23", "", "", "19", "", "23", "", "", "", "", "Bee (Another)", "D802" ],
  [ "D922", "", "", "Special", "Final Audition Episode 1 (Another)", "BanYa", "189", "", "", "10", "19", "", "22", "", "13", "19", "", "23", "", "", "", "", "Final Audition Episode 1 (Another)", "D922" ],
  [ "DA01", "", "", "Special", "Final Audition 3 U.F (Another)", "BanYa", "130.5", "", "", "", "", "", "18", "", "", "", "", "19", "", "", "", "", "Final Audition 3 U.F (Another)", "DA01" ],
  [ "DA02", "", "", "Special", "Naissance 2 (Another)", "BanYa", "129", "", "", "", "", "", "20", "", "", "", "", "19", "", "", "", "", "Naissance 2 (Another)", "DA02" ],
  [ "DB06", "", "", "Special", "Deja Vu (Another)", "Som2", "115", "", "", "", "", "", "17", "", "", "", "", "", "", "", "", "", "Deja Vu (Another)", "DB06" ],
  [ "DB17", "", "", "Special", "Hi-Bi (Another)", "BanYa", "145", "", "", "", "17", "6", "18", "", "", "18", "7", "20", "", "", "", "", "Hi-Bi (Another)", "DB17" ],
  [ "DC03", "", "", "Special", "Witch Doctor (Another)", "BanYa", "195", "", "", "", "21", "", "22", "", "19", "21", "19", "23", "", "", "", "", "Witch Doctor (Another)", "DC03" ],
  [ "DC05", "", "", "Special", "Phantom (Another)", "BanYa", "136", "", "", "", "19", "", "20", "", "", "18", "11", "20", "", "", "", "", "Phantom (Another)", "DC05" ],
  [ "DC11", "", "", "Special", "Do it Yourself (Another)", "LazyBone", "106", "", "", "", "", "", "17", "", "", "", "", "", "", "", "", "", "Do it Yourself (Another)", "DC11" ],
  [ "DC04", "", "", "Special", "Love is a Danger Zone 2 (D&G Ver.) (Another)", "BanYa", "162", "", "", "16", "18", "", "??", "", "16", "17", "??", "??", "", "", "", "", "Love is a Danger Zone 2 (Another)", "DC04" ],
  [ "DD01", "", "", "Special", "Witch Doctor #1 (Another)", "Yahpp", "122", "", "", "18", "20", "19", "21", "", "7", "18", "7", "20", "", "", "", "", "Witch Doctor #1 (Another)", "DD01" ],
  [ "DD03", "", "", "Special", "Chimera (Another)", "Yahpp", "210", "", "", "13", "20", "15", "??", "", "16", "19", "16", "??", "", "", "", "", "Chimera (Another)", "DD03" ],
  [ "DD11", "", "", "Special", "For You (Another)", "N.Ex.T", "160", "", "", "", "", "13", "", "", "", "", "", "", "", "", "", "", "For You (Another)", "DD11" ],
  [ "DD16", "", "", "Special", "Gun Rock (Another)", "BanYa Production", "104", "", "", "", "18", "", "19", "", "", "", "", "", "", "", "", "", "Gun Rock (Another)", "DD16" ],
  [ "DD28", "", "", "Special", "Final Audition Episode 2-1 (Another)", "Yahpp", "170", "", "", "", "20", "", "22", "", "19", "21", "", "22", "", "", "", "", "Final Audition Episode 2-1 (Another)", "DD28" ],
  [ "DD30", "", "", "Special", "Final Audition Episode 2-2 (Another)", "Yahpp", "200", "", "", "16", "21", "18", "25", "", "16", "21", "18", "23", "", "", "", "", "Final Audition Episode 2-2 (Another)", "DD30" ],
  [ "E303", "", "", "Special", "Turkey March (Another)", "BanYa", "150", "", "", "15", "18", "", "", "", "", "", "", "", "", "", "", "", "Turkey March (Another)", "E303" ],
  [ "E404", "", "", "Special", "Solitary (Another)", "BanYa", "136", "", "", "", "17", "", "19", "", "", "17", "", "18", "", "", "", "", "Solitary (Another)", "E404" ],
  [ "E826", "", "", "Special", "Come to Me (Another)", "BanYa", "100-107", "", "", "12", "17", "", "14", "", "", "", "", "", "", "", "", "", "Come to Me (Another)", "E826" ],
  [ "ED08", "", "", "Special", "Free! (Another)", "Jiny", "174.6", "", "", "", "", "5", "", "", "", "", "", "", "", "", "", "", "Free (Another)", "ED08" ],
  [ "ED12", "", "", "Special", "Snow Dream (Another)", "Apple Jam", "170", "", "", "", "", "6", "", "", "", "", "", "", "", "", "", "", "Snow Dream (Another)", "ED12" ],
  [ "ED13", "", "", "Special", "Handsome Character That Pass (Another)", "May", "125", "", "", "", "13", "", "14", "", "", "", "", "", "", "", "", "", "Handsome Character That Pass (Another)", "ED13" ],
  [ "ED18", "", "", "Special", "Ugly Dee (Another)", "BanYa Production", "92", "", "", "", "", "15", "15", "", "", "", "11", "15", "", "", "", "", "Ugly Dee (Another)", "ED18" ],
  [ "ED21", "", "", "Special", "So (Another)", "Typhoon", "138", "", "12", "13", "15", "14", "16", "", "", "", "", "", "", "", "", "", "So (Another)", "ED21" ],
  [ "ED29", "", "", "Special", "Fire (Another)", "Yahpp", "136", "", "", "12", "15", "13", "15", "", "", "", "", "", "", "", "", "", "Fire (Another)", "ED29" ],
  [ "EE03", "", "", "Special", "Caprice of Otada (Another)", "BanYa Production", "160", "", "", "16", "19", "18", "21", "", "17", "19", "19", "21", "", "", "", "", "Caprice of Otada (Another)", "EE03" ],
  [ "EE10", "", "", "Special", "A.U Ready? (Another)", "Gil Gun", "94", "", "", "", "", "12", "15", "", "", "", "13", "16", "", "", "", "", "A.U Ready? (Another)", "EE10" ],
  [ "EE12", "", "", "Special", "Faster Z (Another)", "Yahpp", "162", "", "", "15", "19", "19", "20", "8", "16", "19", "18", "22", "", "", "", "", "Faster Z (Another)", "EE12" ],
  [ "EE13", "", "", "Special", "Pumptris Quattro (Another)", "Yahpp", "153", "", "7", "8", "17", "4", "22", "10", "12", "17", "2", "22", "", "", "", "", "Pumptris Quattro (Another)", "EE13" ],
  [ "EE14", "", "", "Special", "It's My Business (Another)", "Taiji Boys", "200", "", "", "", "10", "", "14", "", "", "14", "", "17", "", "", "", "", "It's My Business (Another)", "EE14" ],
  [ "EE15", "", "", "Special", "You Fell in Me (Another)", "No Brain", "152", "", "", "", "16", "", "18", "", "", "16", "", "17", "", "", "", "", "You Fall in Me (Another)", "EE15" ],
  [ "EE23", "", "", "Special", "Guitar Man (Another)", "BanYa Production", "120", "", "", "", "17", "", "20", "", "", "", "", "", "", "", "", "", "Guitar Man (Another)", "EE23" ],
  [ "EE24", "", "", "Special", "Higgledy Piggledy (Another)", "BanYa Production", "150", "", "", "16", "18", "", "", "", "16", "18", "", "", "", "", "", "", "Higgledy Piggledy (Another)", "EE24" ],
  [ "EE28", "", "", "Special", "Dance Vibrations (Another)", "Elpis", "130", "", "", "", "14", "", "18", "", "", "", "", "", "", "", "", "", "Dance Vibrations (Another)", "EE28" ],
  [ "F302", "", "", "Special", "Naissance (Another)", "BanYa", "135.5", "", "", "", "", "", "", "", "", "20", "", "", "", "", "", "", "Naissance (Another)", "F302" ],
  [ "F516", "", "", "Special", "Slam (Another)", "Novasonic", "136", "", "", "", "", "", "", "", "", "18", "", "19", "", "", "", "", "Slam (Another)", "F516" ],
  [ "F712", "", "", "Special", "Will o' the Wisp (Another)", "BanYa", "210", "", "", "", "", "", "", "", "", "19", "", "21", "", "", "", "", "Will o' the Wisp (Another)", "F712" ],
  [ "F906", "", "", "Special", "Starian (Another)", "Duke", "134.9", "", "", "", "", "", "", "", "", "15", "", "17", "", "", "", "", "Starian (Another)", "F906" ],
  [ "FA08", "", "", "Special", "Dignity (Another)", "Crash", "195", "", "", "", "", "", "", "", "16", "", "", "", "", "", "", "", "Dignity (Another)", "FA08" ],
  [ "FB19", "", "", "Special", "Canon-D (Another)", "BanYa", "160", "", "", "", "", "", "", "", "", "21", "", "21", "", "", "", "", "Canon-D (Another)", "FB19" ],
  [ "FC02", "", "", "Special", "Moonlight (Another)", "BanYa", "180", "", "", "", "", "", "", "", "", "19", "", "21", "", "", "", "", "Moonlight (Another)", "FC02" ],
  [ "FD02", "", "", "Special", "Arch of Darkness (Another)", "Yahpp", "135.9", "", "", "", "", "", "", "", "", "17", "", "", "", "", "", "", "Arch of Darkness (Another)", "FD02" ],
  [ "FE13B", "", "", "Special", "Pumptris Quattro (8bit version) (Another)", "Yahpp", "162", "", "", "", "", "", "", "16", "16", "17", "??", "??", "", "", "", "", "Pumptris Quattro [8bit ver.] (Another)", "FE13B" ],
  [ "F01", "", "", "Special", "Blaze Emotion (Another)", "Yahpp", "170", "", "", "", "", "", "", "", "", "17", "", "18", "", "", "", "", "Blaze Emotion (Another)", "F01" ],
  [ "F02", "", "", "Special", "Cannon X.1 (Another)", "Yahpp", "185", "", "", "", "", "", "", "", "8", "21", "10", "", "", "", "", "", "Cannon X.1 (Another)", "F02" ],
  [ "F09", "", "", "Special", "Chocolate (Another)", "Banana Girl", "130", "", "", "", "", "", "", "", "6", "13", "", "15", "", "", "", "", "Chocolate (Another)", "F09" ],
  [ "F23", "", "", "Special", "DJ Otada (Another)", "BanYa Production", "180", "", "", "", "", "", "", "", "", "20", "", "21", "", "", "", "", "DJ Otada (Another)", "F23" ],
  [ "F25", "", "", "Special", "My Dreams (Another)", "BanYa Production", "136", "", "", "", "", "", "", "", "", "19", "", "", "", "", "", "", "My Dreams (Another)", "F25" ],
  [ "F26", "", "", "Special", "Toccata (Another)", "BanYa Production", "104", "", "", "", "", "", "", "", "16", "17", "", "", "", "", "", "", "Toccata (Another)", "F26" ],


  //{ "ID#", "NX2", "NXA", "Channel", "Song Title", "Artist", "BPM", "Exclusivity", "NL", "HD", "CZ", "FS", "NM", "NL", "HD", "CZ", "FS", "NM", "Training Station (NX2)", "WorldMax (NX2)", "WorldMax (NXA)", "Brain Shower (NXA)", "Song Title", "ID" ],
];

AddCheckTracklist( test_PH_NX2_NXA_tracklist, test_PH_NX2_NXA_special, { channel: 3, title: 4, artist: 5, bpm: 6, NX2: 8, NXA: 13, } );

CheckTracklist( tracklist, test_PH_NX2_NXA_tracklist, { channel: 3, title: 4, artist: 5, bpm: 6, NX2: 8, NXA: 13, } );
